name: Generate Metrics

on:
  schedule:
    - cron: '0 0 * * *'   # once daily
  workflow_dispatch:

jobs:
  github-metrics:
    runs-on: ubuntu-latest
    steps:
      - name: Generate isometric calendar
        uses: lowlighter/metrics@latest
        with:
          token: ${{ secrets.METRICS_TOKEN }}
          filename: metrics.plugin.isocalendar.svg
          base: ""
          plugin_isocalendar: "yes"
          plugin_isocalendar_duration: "full-year"
